---
apiVersion: v1
kind: Secret
metadata:
  name: #{name}#-#{env}#-secrets
  namespace: #{namespace}#-#{env}#
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: #{MYSQL_ROOT_PASSWORD}#
  MYSQL_DATABASE: #{MYSQL_DATABASE}#
  MYSQL_USER: #{MYSQL_USER}#
  MYSQL_PASSWORD: #{MYSQL_PASSWORD}#