---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{name}#-#{env}#-deployment
  namespace: #{namespace}#-#{env}#
  labels:
    app: #{name}#-#{env}#
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #{name}#-#{env}#
  template:
    metadata:
      labels:
        app: #{name}#-#{env}#
    spec:
      containers:
        - name: #{name}#-#{env}#
          image: mysql:5.7
          ports:
            - containerPort: 3306
          volumeMounts:
            - mountPath: "/var/lib/mysql"
              subPath: "#{name}#/mysql"
              name: nfs-#{namespace}#-#{env}#-data
          envFrom:
            - secretRef:
                name: #{name}#-#{env}#-secrets
          resources:
            limits:
              cpu: #{cpu-lim}#
              memory: #{mem-lim}#
            requests:
              cpu: #{cpu-req}#
              memory: #{mem-req}#
      securityContext:
        runAsUser: 1001
      volumes:
        - name: nfs-#{namespace}#-#{env}#-data
          persistentVolumeClaim:
            claimName: nfs-data